name: Build for Linux

on: push

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Prepare builder
        run: sudo apt-get -y install gcc-multilib g++-multilib

      - name: Build it
        run: make -C linux

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: |
            linux/main
